name: synopsis-generator-langgraph

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: synopsis-generator-api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./src:/app/src
      - ./artifacts:/app/artifacts
      - ./logs:/app/logs
    networks:
      - wata-infra
    command:
      - uvicorn
      - app.main:app
      - --host
      - 0.0.0.0
      - --port
      - "8000"
      - --reload


  mcp:
    build:
      context: ./mcp_server
      dockerfile: Dockerfile
    container_name: synopsis-mcp-server
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "127.0.0.1:8001:8001"
    networks:
      - wata-infra


networks:
  wata-infra:
    external: true
