"""add story projects

Revision ID: 36b50a0cf497
Revises: 4d54ee7a7b31
Create Date: 2026-07-23 11:32:01.193248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '36b50a0cf497'
down_revision: Union[str, Sequence[str], None] = '4d54ee7a7b31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('story_projects',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('premise', sa.Text(), nullable=False),
    sa.Column('genre', sa.Text(), nullable=False),
    sa.Column('style', sa.Text(), nullable=False),
    sa.Column('language', sa.Text(), nullable=False),
    sa.Column('memory', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('memory_version', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('story_memory_versions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('story_id', sa.BigInteger(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('memory', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_generation_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_generation_id'], ['synopsis_generations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['story_id'], ['story_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('story_id', 'version', name='uq_story_memory_story_version')
    )
    op.add_column('synopsis_generations', sa.Column('story_id', sa.BigInteger(), nullable=True))
    op.add_column('synopsis_generations', sa.Column('thread_id', sa.Text(), nullable=True))
    op.add_column('synopsis_generations', sa.Column('user_request', sa.Text(), nullable=True))
    op.add_column('synopsis_generations', sa.Column('entry_summary', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'synopsis_generations', 'story_projects', ['story_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'synopsis_generations', type_='foreignkey')
    op.drop_column('synopsis_generations', 'entry_summary')
    op.drop_column('synopsis_generations', 'user_request')
    op.drop_column('synopsis_generations', 'thread_id')
    op.drop_column('synopsis_generations', 'story_id')
    op.drop_table('story_memory_versions')
    op.drop_table('story_projects')
    # ### end Alembic commands ###
